FROM golang:1.26-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/mock-service ./cmd/mock-service

FROM alpine:3.22

WORKDIR /app

COPY --from=build /bin/mock-service /app/mock-service

EXPOSE 9001

ENTRYPOINT ["/app/mock-service"]
